apiVersion: v1
kind: Secret
metadata:
  name: payment
  namespace: roboshop
type: Opaque
data:
  AMQP_USER: cm9ib3Nob3A=
  AMQP_PASS: cm9ib3Nob3AxMjM=


  # 1. AMQP_USER: roboshop
  # 2. AMQP_PASS: roboshop123