apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatch
  namespace: roboshop
  labels: # these labels are deployment labels
    app: dispatch
    project: roboshop
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels: # these labels are used to find the pods
      app: dispatch
      project: roboshop
      tier: db
  template:
    metadata:
      labels: # these labels are pod labels
        app: dispatch
        project: roboshop
        tier: db
    spec:
      containers:
      - name: dispatch
        # image: dispatch:v1.1
        image: lingadevops/dispatch:v1.5
        imagePullPolicy: Always