apiVersion: v1
kind: Service
metadata:
  name: dispatch
  namespace: roboshop
spec:
  selector:
    app: dispatch
    project: roboshop
    tier: db
  ports:
  - protocol: TCP
    port: 6379 #service-port
    targetPort: 6379 #container-port