apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::484907532817:role/eksctl-expense-nodegroup-spot-NodeInstanceRole-Of3wNCN2oza5
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-pod-reader
      userarn: arn:aws:iam::484907532817:user/ramesh
      username: ramesh
    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::484907532817:user/raheem
      username: raheem

kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system